# Setup
title:        Computing for Biologists | SMCM Spring 2025
tagline:       This will be the website for Computing for Biologists for the Spring 2025 semester at St. Marys College of Maryland. All materials will be posted here.
baseurl:      
url:          https://pesalerno.github.io/computing_SP25/
paginate:     1
theme: jekyll-theme-cayman
future: true

# About/contact
author:
 name:       Patricia Salerno
 url:        https://patriciasalerno.wixsite.com/tepui

# Gems
plugins:
  - jekyll-paginate
  
# Google services
google_analytics: UA-144489144-1

#Others
site:
 

